// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_eigen
Rcpp::List fast_eigen(const arma::mat& X);
RcppExport SEXP _GWASBrewer_fast_eigen(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_eigen(X));
    return rcpp_result_gen;
END_RCPP
}
// fast_eigen_vals
arma::vec fast_eigen_vals(const arma::mat& X);
RcppExport SEXP _GWASBrewer_fast_eigen_vals(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_eigen_vals(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GWASBrewer_fast_eigen", (DL_FUNC) &_GWASBrewer_fast_eigen, 1},
    {"_GWASBrewer_fast_eigen_vals", (DL_FUNC) &_GWASBrewer_fast_eigen_vals, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_GWASBrewer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
