# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_eigen <- function(X) {
    .Call(`_GWASBrewer_fast_eigen`, X)
}

fast_eigen_vals <- function(X) {
    .Call(`_GWASBrewer_fast_eigen_vals`, X)
}

